export const packages = [
  {
    id: 1,
    name: "Phuket",
    tag: "Phuket Karbi Gateway",
    days: 5,
    nights: 4,
    price: 25000,
    image: "/images/phuket.avif",
    category: ["beach", "adventure"],
    type: "international",
    country: "Thailand",
    path: "/packages/international/phuket",
    pdfPath: "/pdfs/phuket.pdf",
  },
  {
    id: 2,
    name: "Dubai",
    tag: "Dubai City Tour",
    days: 4,
    nights: 3,
    price: 30000,
    image: "/images/dubai.avif",
    category: ["adventure"],
    type: "international",
    country: "UAE",
    path: "/packages/international/dubai",
    pdfPath: "/pdfs/dubai.pdf",
  },
  {
    id: 3,
    name: "Baku",
    tag: "Baku Adventure",
    days: 5,
    nights: 4,
    price: 28000,
    image: "/images/baku.avif",
    category: ["adventure,mountains"],
    type: "international",
    country: "Azerbaijan",
    path: "/packages/international/baku",
    pdfPath: "/pdfs/baku.pdf",
  },

  // 🇮🇳 Domestic Packages
  {
    id: 4,
    state: "Goa",
    name: "Goa",
    tag: "Goa Beach Escape",
    days: 4,
    nights: 3,
    price: 15000,
    image: "/images/goa.avif",
    category: ["beach", "adventure"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/goa",
    pdfPath: "/pdfs/goa.pdf",
  },
  {
    id: 5,
    name: "Rajasthan",
    state: "Rajasthan",
    tag: "Royal Rajasthan Journey",
    days: 6,
    nights: 5,
    price: 20000,
    image: "/images/rajasthan.avif",
    category: ["adventure,wildlife"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/rajasthan",
    pdfPath: "/pdfs/rajasthan.pdf",
  },
  {
    id: 6,
    name: "Kerala",
    state: "Kerela",
    tag: "Kerala Backwater Bliss",
    days: 6,
    nights: 5,
    price: 22000,
    image: "/images/kerala.avif",
    category: ["beach", "wildlife"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/kerala",
    pdfPath: "/pdfs/kerala.pdf",
  },
  {
    id: 7,
    name: "Kashmir",
    state: "Jammu & kashmir",
    tag: "Heavenly Kashmir Retreat",
    days: 5,
    nights: 4,
    price: 24000,
    image: "/images/kashmir.avif",
    category: ["mountains"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/kashmir",
    pdfPath: "/pdfs/kashmir.pdf",
  },
  {
    id: 8,
    name: "Himachal",
    state: "Himanchal",
    tag: "Himachal Hills & Thrills",
    days: 5,
    nights: 4,
    price: 21000,
    image: "/images/himachal.avif",
    category: ["mountains", "adventure"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/himachal",
    pdfPath: "/pdfs/himachal.pdf",
  },
  {
    id: 9,
    name: "Uttarakhand",
    state: "Uttrakhand",
    tag: "Spiritual Uttarakhand Escape",
    days: 5,
    nights: 4,
    price: 20000,
    image: "/images/uttarakhand.avif",
    category: ["mountains", "pilgrim"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/uttarakhand",
    pdfPath: "/pdfs/uttarakhand.pdf",
  },
  {
    id: 10,
    name: "Darjeeling & Assam",
    state: "Assam",
    tag: "Tea Garden & Wildlife Trail",
    days: 6,
    nights: 5,
    price: 23000,
    image: "/images/darjeeling-assam.avif",
    category: ["mountains", "wildlife"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/darjeeling-assam",
    pdfPath: "/pdfs/darjeeling-assam.pdf",
  },
  {
    id: 11,
    name: "Coorg",
    state: "Karnataka",
    tag: "Coorg Nature Retreat",
    days: 4,
    nights: 3,
    price: 17000,
    image: "/images/coorg.avif",
    category: ["mountains", "wildlife"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/coorg",
    pdfPath: "/pdfs/coorg.pdf",
  },
  {
    id: 12,
    name: "Meghalaya",
    state: "Meghalaya",
    tag: "Mystic Meghalaya Adventure",
    days: 5,
    nights: 4,
    price: 21000,
    image: "/images/meghalaya.avif",
    category: ["mountains", "wildlife", "adventure"],
    type: "domestic",
    country: "India",
    path: "/packages/domestic/meghalaya",
    pdfPath: "/pdfs/meghalaya.pdf",
  },
];

export const specificPackage = [
  {
    id: 1,
    state: "Himachal",
    bannerImg:"/images/shimla-manali.avif",
    galleryImg:"/images/shimla-manali-gallery.avif",
    packageName: "Shimla-Manali",
    tag:"Spectular Shimla-Manali Getaway",
    highlight1:["Bunjee Jumping at Solang Valley","Manali",2],
    highlight2:["Visit to Naggar Castle","Shimla",4],
    highlightImg:"/images/manali-shimla-highlight.avif",
    by: "cab",
    days: 6,
    nights: 5,
    meals:6,
    hotels:2,
    activities:4,
    transportation:"CAB",
    pick: "Delhi",
    drop: "Delhi",
    car: "Swift Desire / Etios",
    pax: 6,
    deluxPrice:34000,
    deluxSalePrice: 23999,
    priceLuxury: null, // Can add later if available
    room: 1,
    meal: "Breakfast and Dinner only",
    dest1: "Shimla",
    dest1Timing: 2,
    dest2: "Manali",
    dest2Timing: 3,
    dest3: null,
    dest3Timing: null,
    dest4: null,
    dest4Timing: null,
    seasonTime: "15th April to 5th July, 15th Dec to 5th January",
    offSeasonTime: "15th July to 30th September, 6th January to 15th April",
    hotelDest1: "Swastik Inn / Satyam Grand / Apple Rose",
    hotelDest2: "Suvidha Cottage / Mountain Crest / Acharya Cottage / Royal Rajput",
    luxuryHotelDest1: "Whistling Pines Resort / Baljees Regency / Hotel Royal Regency",
    luxuryHotelDest2: "Rohtang Heights / Holiday Height / Himalayan Heights / Thomas Villa",

    itinerary: [
      {
        day: 1,
        image:"/images/shimla-manali-day1.avif",
        place:"Shimla",
        title: "Delhi/Chandigarh Pickup - Shimla",
        meal: "Dinner only",
        description:
          "On arrival at Chandigarh/Delhi Airport or Railway Station, meet our driver and drive to Shimla, the 'Queen of Hills'. On arrival, check-in at the hotel, relax and explore nearby places.",
        mainAttractions: []
      },
      {
        day: 2,
        image:"/images/shimla-manali-day2.avif",
        place:"Shimla",
        title: "Shimla - Kufri - Local Sightseeing",
        meal: "Breakfast & Dinner",
        description:
          "After breakfast, visit Green Valley, Mini Zoo, Wild Flower Hall, Chini Banglow, Faggu Valley View, Apple Garden, Indira Gandhi Tourist Park, Fun World, Jakhoo Temple, Mall Road, Christ Church, Scandal Point, Wooden Market, Kali Bari Temple and Tibetan Market. Overnight at hotel.",
        mainAttractions: [
          "Kufri",
          "Hassan Valley",
          "Fun World (Activities Point)",
          "Himalayan Nature Park",
          "Indira Tourist Park",
          "Chini Bungalow",
          "Mashu Peak",
          "Fagu Valley",
          "Mini Zoo",
          "Mall Road",
          "Christ Church",
          "Scandal Point",
          "Kali Bari Temple",
          "Tibetan Market",
          "The Ridge",
          "Lakkar Bazaar",
          "Jakhoo Temple"
        ]
      },
      {
        day: 3,
         image:"/images/shimla-manali-day3.avif",
        title: "Shimla - Manali via Kullu Valley",
        place:"Manali",
        meal: "Breakfast & Dinner",
        description:
          "After breakfast, check out and drive to Manali. On the way visit Sundernagar Lake, Pandoh Dam, Vaishno Devi Temple, and Kullu Shawl Factory. On arrival check-in at the hotel and relax.",
        mainAttractions: [
          "Sundernagar Lake",
          "Pandoh Dam",
          "Vaishno Devi Temple",
          "Kullu Shawl Factory",
          "Beas River (Optional River Rafting)"
        ]
      },
      {
        day: 4,
         image:"/images/shimla-manali-day4.avif",
        place:"Manali",
        title: "Manali - Local Sightseeing",
        meal: "Breakfast & Dinner",
        description:
          "After breakfast, enjoy local sightseeing of Manali. Visit Hidimba Devi Temple, Manu Temple, Club House, Tibetan Monastery, Van Vihar, and Vashisth Hot Springs. Explore Old Manali and Mall Road.",
        mainAttractions: [
          "Hidimba Devi Temple",
          "Manu Temple",
          "Club House",
          "Tibetan Monastery",
          "Van Vihar National Park",
          "Vashisth (Hot Spring)",
          "Old Manali",
          "Mall Road",
          "Tibetan Market"
        ]
      },
      {
        day: 5,
         image:"/images/shimla-manali-day5.avif",
        place:"Manali",
        title: "Manali - Solang Valley - Anjani Mahadev",
        meal: "Breakfast & Dinner",
        description:
          "After breakfast, drive to Solang Valley. En route visit Nehru Kund and up to snow point. Enjoy activities like paragliding and ropeway at your own cost. Visit Anjani Mahadev Temple. Return to hotel.",
        mainAttractions: ["Solang Valley", "Nehru Kund", "Anjani Mahadev"]
      },
      {
        day: 6,
         image:"/images/shimla-manali-day6.avif",
        place:"Manali",
        title: "Naggar Castle - Delhi Drop",
        meal: "Breakfast",
        description:
          "After breakfast, check out and visit Naggar Castle (or Manikaran as optional). Later, drive to Chandigarh/Delhi for your return journey with unforgettable memories.",
        mainAttractions: ["Naggar Castle", "Optional: Manikaran Hot Springs & Temples"]
      }
    ]
  }
];

export const categories = [
  { id: "beach", image: "/images/C1.avif",path:"/categories/beach"},
  { id: "mountains", image: "/images/C2.avif",path:"/categories/mountains" },
  { id: "adventure", image: "/images/C3.avif",path:"/categories/adventure" },
  { id: "pilgrim", image: "/images/C4.avif",path:"/categories/pilgrim"},
  { id: "wildlife", image: "/images/C5.avif",path:"/categories/wildlife" },
];
